#!/bin/bash
####################
##     update     ##
#########################################
## Обновление приложения данными с GIT ##
#########################################
: 'Оглавление

  1. Определить название группы конфигов для запуска приложения
  2. Обновить приложение

'
#########################################

# 1. Определить название группы конфигов для запуска приложения
# - Которую надо будет применить для запуска приложения

  # 1.1. Подготовить значение по умолчанию
  cogfigs_group=$cogfigs_group_default

  # 1.2. Если команде update переданы какие-то опции
  if [ $# != 0 ]; then
    
    # Провести парсинг этих опций
    OPTIND=1
    while getopts ":c:" opt; do
      case $opt in

        # Если опция -c передана
        c)
          # Если:
          # - Значение опции -c не пусто
          # - Существует группа опций с таким именем
          # То:
          # - Записать это значение в $cogfigs_group
          if [ -n "$OPTARG" ] && [ -d "$PWD/configs/groups/$OPTARG" ]; then
            cogfigs_group=$OPTARG
          fi
          ;;
      esac
    done      

  fi

# 2. Обновить приложение    
. app down
. app up -c "$cogfigs_group"
cd project
artisan m1:update_forks
cd ..
. app down
ssh -T git@github.com
git stash
git submodule foreach 'git stash'
git pull
git submodule foreach 'git stash'
git submodule update --recursive --remote
chmod -R 777 .
. app up -c "$cogfigs_group"


